login:
  username: ''
  password: ''
urls:
  userLogin: 'https://auth.tesla.com/login'
  userLogout: 'https://www.tesla.com/user/logout'
tesla:
  reservation: ''
puppet:
  headless: true
  args:
    - '--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36'
    - '--no-sandbox'
    - '--disable-setuid-sandbox'
    - '--disable-gpu'
    - '--disable-dev-shm-usage'
twilio:
  accountSid: ''
  authToken: ''
  phoneFrom: ''
  phoneTo: ''
discord:
  id: ''
  token: ''
interval:
  minutes: 300
